import { Product } from "../models/products";

export const productsDataSource: Product[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro',
    description: 'O mais avançado iPhone com chip A17 Pro, câmera de 48MP e design em titânio.',
    price: 1299.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=iPhone+15+Pro',
    rating: 4.8,
    reviewsCount: 1250,
    inStock: true,
    category: 'Smartphones',
    brand: 'Apple',
    stock: 45,
    createdAt: new Date('2023-09-15'),
    updatedAt: new Date('2023-09-15')
  },
  {
    id: '2',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Smartphone premium com S Pen, câmera de 200MP e tela Dynamic AMOLED 2X.',
    price: 1199.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=Galaxy+S24+Ultra',
    rating: 4.7,
    reviewsCount: 980,
    inStock: true,
    category: 'Smartphones',
    brand: 'Samsung',
    stock: 32,
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-17')
  },
  {
    id: '3',
    name: 'MacBook Pro 14" M3',
    description: 'Laptop profissional com chip M3, tela Liquid Retina XDR e até 22 horas de bateria.',
    price: 1999.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=MacBook+Pro+14',
    rating: 4.9,
    reviewsCount: 756,
    inStock: true,
    category: 'Laptops',
    brand: 'Apple',
    stock: 18,
    createdAt: new Date('2023-10-30'),
    updatedAt: new Date('2023-10-30')
  },
  {
    id: '4',
    name: 'Dell XPS 13',
    description: 'Ultrabook premium com processador Intel Core i7, tela InfinityEdge e design elegante.',
    price: 1499.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=Dell+XPS+13',
    rating: 4.6,
    reviewsCount: 623,
    inStock: true,
    category: 'Laptops',
    brand: 'Dell',
    stock: 25,
    createdAt: new Date('2023-11-15'),
    updatedAt: new Date('2023-11-15')
  },
  {
    id: '5',
    name: 'Sony WH-1000XM5',
    description: 'Fones de ouvido premium com cancelamento de ruído líder da indústria e 30h de bateria.',
    price: 399.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=Sony+WH-1000XM5',
    rating: 4.8,
    reviewsCount: 1840,
    inStock: true,
    category: 'Audio',
    brand: 'Sony',
    stock: 67,
    createdAt: new Date('2022-05-12'),
    updatedAt: new Date('2022-05-12')
  },
  {
    id: '6',
    name: 'iPad Air 5ª Geração',
    description: 'Tablet versátil com chip M1, tela Liquid Retina de 10.9" e suporte ao Apple Pencil.',
    price: 599.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=iPad+Air+5',
    rating: 4.7,
    reviewsCount: 892,
    inStock: true,
    category: 'Tablets',
    brand: 'Apple',
    stock: 41,
    createdAt: new Date('2022-03-08'),
    updatedAt: new Date('2022-03-08')
  },
  {
    id: '7',
    name: 'Nintendo Switch OLED',
    description: 'Console portátil com tela OLED de 7", Joy-Cons e dock para TV com 64GB de armazenamento.',
    price: 349.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=Nintendo+Switch+OLED',
    rating: 4.5,
    reviewsCount: 2156,
    inStock: true,
    category: 'Gaming',
    brand: 'Nintendo',
    stock: 73,
    createdAt: new Date('2021-10-08'),
    updatedAt: new Date('2021-10-08')
  },
  {
    id: '8',
    name: 'Apple Watch Series 9',
    description: 'Relógio inteligente com chip S9, tela Always-On Retina e monitoramento avançado de saúde.',
    price: 399.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=Apple+Watch+Series+9',
    rating: 4.6,
    reviewsCount: 1347,
    inStock: true,
    category: 'Wearables',
    brand: 'Apple',
    stock: 89,
    createdAt: new Date('2023-09-22'),
    updatedAt: new Date('2023-09-22')
  },
  {
    id: '9',
    name: 'LG OLED C3 55"',
    description: 'TV OLED 4K com processador α9 AI Processor Gen6, Dolby Vision IQ e webOS 23.',
    price: 1599.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=LG+OLED+C3+55',
    rating: 4.8,
    reviewsCount: 567,
    inStock: false,
    category: 'TVs',
    brand: 'LG',
    stock: 0,
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2024-01-10')
  },
  {
    id: '10',
    name: 'Canon EOS R6 Mark II',
    description: 'Câmera mirrorless full-frame com sensor de 24.2MP, gravação 4K 60p e estabilização de imagem.',
    price: 2499.99,
    imageUrl: 'https://via.placeholder.com/300x300?text=Canon+EOS+R6+Mark+II',
    rating: 4.9,
    reviewsCount: 423,
    inStock: true,
    category: 'Cameras',
    brand: 'Canon',
    stock: 12,
    createdAt: new Date('2022-11-02'),
    updatedAt: new Date('2022-11-02')
  }
] as Product[];
